# 异常处理

实例：

```python
try:
    fh = open("testfile", "w")
    fh.write("这是一个测试文件，用于测试异常!!")
except IOError:
    print "Error: 没有找到文件或读取文件失败"
else:
    print "内容写入文件成功"
    fh.close()
```

try-except

```python
try:
    正常的操作
except(Exception1[, Exception2[,...ExceptionN]]):
   发生以上多个异常中的一个，执行这块代码
else:
    如果没有异常执行这块代码
```

try-finally

```python
try:
    <语句>
finally:
    <语句>    #退出try时总会执行
raise
```

raise：自己触发异常

```python
raise [Exception [, args [, traceback]]]
```

常用异常

| 错误类型          | 说明                                                         |
| ----------------- | ------------------------------------------------------------ |
| AttributeError    | 试图访问一个对象没有的属性，比如foo.x，但是foo没有属性x      |
| IOError           | 输入/输出异常；基本上是无法打开文件                          |
| ImportError       | 无法引入模块或包；基本上是路径问题或名称错误                 |
| IndentationError  | 语法错误（的子类）；代码没有正确对齐                         |
| IndexError        | 下标索引超出序列边界，比如当x只有三个元素，却试图访问x[5]    |
| KeyError          | 试图访问字典里不存在的键                                     |
| KeyboardInterrupt | Ctrl+C被按下                                                 |
| NameError         | 使用一个还未被赋予对象的变量                                 |
| TypeError         | 传入对象类型与要求的不符合                                   |
| ValueError        | 传入一个调用者不期望的值，即使值的类型是正确的               |
| UnboundLocalError | 试图访问一个还未被设置的局部变量，基本上是由于另有一个同名的全局变量，导致你以为正在访问它 |

